### ISSUE TITLE
Timeout when installing chart which takes longer then 45 secs

### ISSUE THREAD

**Issue by rachit1arora** [appscode/swift#128]
We have done Swift setup using helm installation and we are using Swift Chart version swift-0.7.0 for our testing. 

We see one issue when we try to install a chart which takes longer to finish our request get timed out. 
Here are the relevant swift logs 

I0511 10:00:40.896296       1 resolver_conn_wrapper.go:68] dialing to target with scheme: ""
I0511 10:00:40.896387       1 resolver_conn_wrapper.go:117] ccResolverWrapper: sending new addresses to cc: [{tiller-deploy.kube-system.svc:44134 0  <nil>}]
I0511 10:00:40.896401       1 clientconn.go:741] ClientConn switching balancer to "pick_first"
I0511 10:00:40.896443       1 pickfirst.go:71] pickfirstBalancer: HandleSubConnStateChange: 0xc42037f8b0, CONNECTING
I0511 10:00:40.902847       1 pickfirst.go:71] pickfirstBalancer: HandleSubConnStateChange: 0xc42037f8b0, READY
I0511 10:00:40.903014       1 chart.go:51] [Chart dir: /tmp/swift053391067]
I0511 10:00:40.903050       1 chart.go:60] [Chart url: http://XXXXXXX.tgz]
I0511 10:00:40.903086       1 chart.go:186] [Downloading http://XXXXXXXX.tgz]
I0511 10:00:40.917937       1 chart.go:268] [1867 bytes downloaded]
I0511 10:01:27.016064       1 handler.go:131] Failed to write response: write tcp 172.30.111.37:9855->172.30.187.247:39126: i/o timeout

Please note that if we install our chart using helm client , it works fine but we see this time out issues when using Swift . 

Can you help us debug this issue? Why we see this timeout in 45 sec ?
After reading Swift documentation we are under impression that there is default time out of 5 min for tiller to respond back .

Let me know if you need more details !!

**Comment by rachit1arora** [comment]
Just to add more details about the log messages . Out Tiller port is 44134 and the Port where we see timeout error is unknown 39126. 
We do not have any svc running on this port. What is this port where swift is trying to connect ?

**Comment by tamalsaha** [comment]
@rachit1arora, were you able to find a solution?

**Comment by tamalsaha** [comment]
Closed due to inactivity
