### ISSUE TITLE
err with too many colons

### ISSUE THREAD

**Issue by jeffchanjunwei** [appscode/swift#135]
How can I solve this error showed as bellow.  My tiller version is 2.7.2 swift version 0.5.2, and after go build it , run with "/swift run --v=3 --connector=direct --tiller-endpoint=http://10.244.3.172:44134"  It is defferent in v0.5.2 of the endpoint-address ?

2018/06/08 07:54:16 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: address http://10.244.3.172:44134: too many colons in address"; Reconnecting to {http://10.244.3.172:44134 <nil>}
2018/06/08 07:54:17 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: address http://10.244.3.172:44134: too many colons in address"; Reconnecting to {http://10.244.3.172:44134 <nil>}
2018/06/08 07:54:18 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: address http://10.244.3.172:44134: too many colons in address"; Reconnecting to {http://10.244.3.172:44134 <nil>}
2018/06/08 07:54:50 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: address http://10.244.3.172:44134: too many colons in address"; Reconnecting to {http://10.244.3.172:44134 <nil>}
2018/06/08 07:54:51 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: address http://10.244.3.172:44134: too many colons in address"; Reconnecting to {http://10.244.3.172:44134 <nil>}
2018/06/08 07:54:53 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: address http://10.244.3.172:44134: too many colons in address"; Reconnecting to {http://10.244.3.172:44134 <nil>}
2018/06/08 07:54:55 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: address http://10.244.3.172:44134: too many colons in address"; Reconnecting to {http://10.244.3.172:44134 <nil>}
2018/06/08 07:54:56 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: address http://10.244.3.172:44134: too many colons in address"; Reconnecting to {http://10.244.3.172:44134 <nil>}
2018/06/08 07:54:58 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: address http://10.244.3.172:44134: too many colons in address"; Reconnecting to {http://10.244.3.172:44134 <nil>}
2018/06/08 07:55:00 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: address http://10.244.3.172:44134: too many colons in address"; Reconnecting to {http://10.244.3.172:44134 <nil>}

**Comment by tamalsaha** [comment]
@jeffchanjunwei, were you able to solve this issue?

**Comment by jeffchanjunwei** [comment]
yes，http://ip:port should be replaced with ip:port only
