### ISSUE TITLE
Add endpoint to get values from release

### ISSUE THREAD

**Issue by david92rl** [appscode/swift#23]
At the moment, the only way to get the values from a specific release is calling `/tiller/v2/releases/my-release/content/json`. It returns an object which contains:

- `release.chart.values.raw` (The content of values.yaml)
- `release.config.raw` (The values passed with `-f` or `--set`)

Both fields are strings containing the helm's yaml response.

It would be great to have an endpoint like `/tiller/v2/releases/my-release/values/json?all=true&revision=X` returning the values in JSON format.

**Comment by tamalsaha** [comment]
@david92rl , we have pushed 0.2.0-rc.0 https://github.com/appscode/swift/releases/tag/0.2.0-rc.0

This can convert the values to JSON by passing query parameter `format_values_as_json=true` 
https://github.com/appscode/swift/blob/833976373232c7b5a970ed14001090bf66ee6e23/_proto/swift/v2/tiller.proto#L258

Let me know is that make it easier to use.
