### ISSUE TITLE
Wrong yamls file addresses in install.md

### ISSUE THREAD

**Issue by BehnamLoghmani** [appscode/swift#62]
files linked in install.md document bring users to the problematic kubernetes files (without-rbac.yaml, with-rbac.yaml)
https://raw.githubusercontent.com/appscode/swift/0.4.0/hack/deploy/without-rbac.yaml
https://raw.githubusercontent.com/appscode/swift/0.4.0/hack/deploy/with-rbac.yaml

links should be updated

**Comment by tamalsaha** [comment]
It has been updated. Can you check again?

**Comment by tamalsaha** [comment]
Fixed in #58
