### ISSUE TITLE
How can I install a release by specifying a local chart folder ?

### ISSUE THREAD

**Issue by YangYongZhi** [appscode/swift#67]
How can I install a chart to tiller with a local folder which contains template yaml files and values yaml file? 

I only found a way to install a chart with url:
`POST http://127.0.0.1:9855/tiller/v2/releases/my-release/json

{
	"chart_url": "https://github.com/tamalsaha/test-chart/raw/master/test-chart-0.1.0.tgz",
	"values": {
		"raw": "{\"ns\":\"c10\",\"clusterName\":\"h505\"}"
	}
}`

somebody can help me? thanks.

**Comment by tamalsaha** [comment]
Local folders are not supported. I am not sure how will it work even if we want to support it.

**Comment by YangYongZhi** [comment]
My chart files are stored in a git repository, and a git repo supplied a URL, you can download a tar file with this URL, e.g.  
`http://gitlab.com/arch/wolverine-app-charts-online/repository/archive.tar.gz?ref=master`
this tar file contains a root path named "wolverine-app-charts-online.git", all charts files are children of this root path. If I pass this URL as the 'chart_url' argument, I guess there will be an error,  because the level of chart folder is wrong.

**Comment by tamalsaha** [comment]
One think you can do is upload the chart.tar.gz file in your git repo. Given these are just YAML files, the tar file should be very small. We do that here for our test chart https://github.com/appscode/swift/tree/master/test/hello

**Comment by YangYongZhi** [comment]
I got it, I think this is a good ideal.
If the chart file has changed for some reason, I repackage this tar file again and commit it.

I will try it with your advice. Thank you.
