### ISSUE TITLE
Can not pass a range value as '--set' argument with swift proxy?

### ISSUE THREAD

**Issue by YangYongZhi** [appscode/swift#70]
My test pod has multiple containers, so I need to pass a image version to each container,
the command when using helm client is like this:
`/usr/local/bin/helm install --set images[0]=latest,deployment.annotation.annotations.buildNumber_0=latest,deployment.annotation.annotations.gitCommit_0=ffffffffff ./$app_name`

it worked successfully.
 
But I install a chart with swift by posting a http request with the parameter like this:
`{"values":{"raw":"{\"replicaCount\":2,\"images[0]\":\"2\",\"deployment.annotation.annotations.buildNumber_0\":\"latest\",\"deployment.annotation.annotations.gitCommit_0\":\"ffffffffff\"}"},"chart_url":"http://gitlab.dmall.com/arch/wolverine-app-charts/raw/nginx-test/nginx.tar.gz"}`

there is an exception returned to me:
`{"code":2,"message":"render error in \"nginx/templates/deployment.yaml\": template: nginx/templates/deployment.yaml:49:55: executing \"nginx/templates/deployment.yaml\" at \u003cindex $images $index\u003e: error calling index: index of untyped nil"}`

My deployment.yaml : 
` containers:
        {{- $images := .Values.images -}}
      	{{- range $index, $container := .Values.containers }}
        - name: {{ $container.name }}-{{ $index }}
          image: "{{ $container.image.repository }}:{{ index $images $index }}"
          imagePullPolicy: {{ $container.image.pullPolicy }}
......`

it looks like tiller have not got a value with key 'images', maybe my request parameter was wrong? How can I pass a range value as the '--set' parameter to the tiller sever with swift proxy?

Thanks.

**Comment by tamalsaha** [comment]
From `/usr/local/bin/helm install --set images[0]=latest,deployment.annotation.annotations.buildNumber_0=latest,deployment.annotation.annotations.gitCommit_0=ffffffffff ./$app_name`
command, I think the YAML values you are passing is:

```yaml
images:
  - latest
deployment:
  annotation:
    annotations:
      buildNumber_0: latest
      gitCommit_0: ffffffffff
```

When converted to json this becomes,
```json
{
  "images": [
    "latest"
  ],
  "deployment": {
    "annotation": {
      "annotations": {
        "buildNumber_0": "latest",
        "gitCommit_0": "ffffffffff"
      }
    }
  }
}

```

**Comment by tamalsaha** [comment]
Closing as this is fixed, according to our conversation on slack.

**Comment by YangYongZhi** [comment]
Thank you for your help,@tamalsaha ,
it can work now.
The raw must be a json string, so I generate it like this instead of old way:
` Map<String, Object> values = new HashMap<>();
            values.put("replicaCount", 1);

            values.put("images", Arrays.asList("v2"));

            Map annotations = new HashMap();
            annotations.put("buildNumber_0", "latest");
            annotations.put("gitCommit_0", "ffffffffff");

            Map annotation = new HashMap();
            annotation.put("annotations", annotations);

            Map deployment = new HashMap();
            deployment.put("annotation", annotation);

            values.put("deployment", deployment);

             String valuesStr = JSON.toJSONString(values);
        Map paramValues = new HashMap();
        paramValues.put("raw", valuesStr);
        params.put("values", paramValues);
        final String parameters = JSON.toJSONString(params);`

The final request body : 
`{"values":{"raw":"{\"replicaCount\":1,\"images\":[\"v2\"],\"deployment\":{\"annotation\":{\"annotations\":{\"gitCommit_0\":\"ffffffffff\",\"buildNumber_0\":\"latest\"}}}}"},"chart_url":"http://gitlab.dmall.com/arch/wolverine-app-charts/raw/nginx-test/nginx.tar.gz"}`

Thank you again.
